const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {initializeApp}=require('firebase-admin/app');
const {getDatabase}=require('firebase-admin/database');
const {randomInt,randomUUID}=require('node:crypto');
const core=require('./secure-core.cjs');initializeApp();const db=getDatabase(),ROOT='formwheelV2';
function callable(handler){return onCall({region:'asia-northeast3',enforceAppCheck:true},async request=>{try{const uid=core.identity(request.auth);if((await db.ref(`${ROOT}/bans/${uid}`).get()).exists())throw new HttpsError('permission-denied','이용이 제한된 계정입니다.');return await handler(request,uid)}catch(e){if(e instanceof HttpsError)throw e;throw new HttpsError(e.code==='permission-denied'?'permission-denied':'failed-precondition',String(e.message||'처리 실패'))}})}
async function limit(uid,action){const now=Date.now(),target=db.ref(`${ROOT}/rateLimits/${uid}/${action}`);const result=await target.transaction(value=>{if(value&&now-value.at<1000)return;return{at:now}});if(!result.committed)throw new HttpsError('resource-exhausted','잠시 후 다시 시도하세요.')}
exports.createSecureRoom=callable(async(request,uid)=>{
 await limit(uid,'create');const input=request.data||{},kind=input.kind;if(!['quiz','battle','vote','spy'].includes(kind))throw new Error('지원하는 게임을 선택하세요.');
 const name=String(input.nickname||'').trim().slice(0,12);if(!name)throw new Error('닉네임을 입력하세요.');let questions=[],answers={},choices=[];
 if(['quiz','battle'].includes(kind)){if(!Array.isArray(input.questions)||input.questions.length<1||input.questions.length>50)throw new Error('문항은 1~50개입니다.');questions=input.questions.map((q,i)=>{if(!Array.isArray(q.choices)||q.choices.length<2||q.choices.length>6||!Number.isInteger(q.correct)||q.correct<0||q.correct>=q.choices.length)throw new Error('문항 선택지를 확인하세요.');answers[i+1]={correct:q.correct};return{id:i+1,prompt:String(q.prompt||'').slice(0,300),choices:q.choices.map(v=>String(v).slice(0,100))}})}
 if(kind==='vote'){if(!Array.isArray(input.choices)||input.choices.length<2||input.choices.length>10)throw new Error('선택지는 2~10개입니다.');choices=input.choices.map(v=>String(v).slice(0,100))}
 const id=randomUUID(),room={version:2,kind,host:uid,status:'lobby',createdAt:Date.now(),players:{[uid]:{uid,name,score:0}},questions,choices,round:0};
 await db.ref().update({[`${ROOT}/rooms/${id}`]:room,[`${ROOT}/privateRooms/${id}/answers`]:answers,[`${ROOT}/privateRooms/${id}/word`]:kind==='spy'?String(input.word||'바다').slice(0,80):null});return{roomId:id};
});
exports.joinSecureRoom=callable(async(request,uid)=>{await limit(uid,'join');const id=core.identifier(request.data?.roomId),name=String(request.data?.nickname||'').trim().slice(0,12);if(!name)throw new Error('닉네임을 입력하세요.');const result=await db.ref(`${ROOT}/rooms/${id}`).transaction(room=>{if(!room||room.status!=='lobby'||Object.keys(room.players||{}).length>=16)return;room.players[uid]={uid,name,score:0};return room});if(!result.committed)throw new Error('참가 가능한 방이 아닙니다.');return{joined:true}});
exports.startSecureRoom=callable(async(request,uid)=>{await limit(uid,'start');const id=core.identifier(request.data?.roomId),target=db.ref(`${ROOT}/rooms/${id}`),generation=randomUUID();const result=await target.transaction(room=>{if(!room||room.host!==uid||room.status!=='lobby'||Object.keys(room.players||{}).length<2)return;room.status='starting';room.generation=generation;return room});if(!result.committed)throw new Error('방장과 참가 인원을 확인하세요.');const room=result.snapshot.val(),patch={};
 if(room.kind==='spy'){const word=(await db.ref(`${ROOT}/privateRooms/${id}/word`).get()).val(),roles=core.assignSpy(room.players,word);for(const [player,role] of Object.entries(roles))patch[`${ROOT}/privatePlayers/${id}/${player}`]=role}
 const start=Date.now()+3000;patch[`${ROOT}/rooms/${id}/status`]='playing';patch[`${ROOT}/rooms/${id}/round`]=1;patch[`${ROOT}/rooms/${id}/startedAt`]=start;patch[`${ROOT}/rooms/${id}/deadline`]=start+30000;await db.ref().update(patch);return{startedAt:start};
});
exports.submitSecureAnswer=callable(async(request,uid)=>{const input=request.data||{},id=core.identifier(input.roomId);if(!Number.isInteger(input.round)||input.round<1||input.round>50)throw new Error('잘못된 라운드');const secret=(await db.ref(`${ROOT}/privateRooms/${id}/answers/${input.round}`).get()).val();if(!secret)throw new Error('정답 데이터가 없습니다.');const result=await db.ref(`${ROOT}/rooms/${id}`).transaction(room=>core.submitAnswer(room,uid,input,secret,Date.now()));return{answer:result.snapshot.val().answers?.[input.round]?.[uid]}});
exports.castSecureVote=callable(async(request,uid)=>{const input=request.data||{},id=core.identifier(input.roomId);const result=await db.ref(`${ROOT}/rooms/${id}`).transaction(room=>core.castVote(room,uid,input.choice,Date.now()));return{counts:result.snapshot.val().counts}});
exports.nextSecureRound=callable(async(request,uid)=>{const id=core.identifier(request.data?.roomId);const result=await db.ref(`${ROOT}/rooms/${id}`).transaction(room=>{if(!room||room.host!==uid||!['quiz','battle'].includes(room.kind)||room.status!=='playing')return;const answers=room.answers?.[room.round]||{};if(Date.now()<room.deadline&&Object.keys(room.players).some(p=>!answers[p]))return;if(room.round>=room.questions.length){room.status='finished';return room}room.round++;room.startedAt=Date.now()+3000;room.deadline=room.startedAt+30000;return room});if(!result.committed)throw new Error('현재 라운드가 끝나지 않았습니다.');return{advanced:true}});
exports.walletAction=callable(async(request,uid)=>{await limit(uid,'wallet');const input=request.data||{},outcome=randomInt(2)===0?'heads':'tails';const result=await db.ref(`${ROOT}/wallets/${uid}`).transaction(wallet=>core.walletAction(wallet,uid,input,Date.now(),outcome));const wallet=result.snapshot.val();return{coins:wallet.coins,receipt:wallet.receipts[input.receipt],inventory:wallet.inventory,equipped:wallet.equipped}});
exports.producerBan=callable(async(request,uid)=>{core.producer(request.auth);const target=core.identifier(request.data?.uid);if(target===uid)throw new Error('본인 계정은 대상에서 제외합니다.');await db.ref(`${ROOT}/bans/${target}`).set({at:Date.now(),by:uid,reason:String(request.data?.reason||'').slice(0,200)});return{banned:true}});
